### ISSUE TITLE
Optimize css styles

### ISSUE THREAD

**Issue by PaoGon** [PaoGon/R.I.M.#17]
### Tasks:

- [ ] put all repeated css attributes on the general styles.css file

#### example:
```css
/* instead of having this repeatedly */ 
.carFlex{
  display: flex;
  align-items:  center;
  justify-content: center;
}


/*just  make something  like this in general css fie*/
.flex-box{
  display: flex;
  align-items:  center;
  justify-content: center;
}
```
